### ISSUE TITLE
The grinder isn't working

### ISSUE THREAD

**Issue by xnaruto546** [Eng1N33R/MechanicalTech#22]
If it helps, I'm on Mac. I tried hooking it up to both waterwheel and wind turbines, but it doesn't seem to work.
![Screen Shot 2021-03-24 at 11 28 46 PM](https://user-images.githubusercontent.com/81348104/112429018-fea4e500-8d33-11eb-8e16-d145fe951f09.png)
![Screen Shot 2021-03-24 at 11 32 53 PM](https://user-images.githubusercontent.com/81348104/112429056-0cf30100-8d34-11eb-82bf-35d2c17d52ff.png)
(Waterwheel)
![Screen Shot 2021-03-24 at 11 32 15 PM](https://user-images.githubusercontent.com/81348104/112429096-1bd9b380-8d34-11eb-82f6-b047832efce9.png)
![Screen Shot 2021-03-24 at 11 32 38 PM](https://user-images.githubusercontent.com/81348104/112429111-21cf9480-8d34-11eb-8222-a7ad2b5db2cb.png)
(Wind Turbine)
It's just a problem with the grinder, everything else is working fine.

**Comment by EngiN33R** [comment]
Hey! Thank you for the feedback!

Currently, the Grinder makes grit (dust) from iron and gold ore blocks, not ingots. I will definitely expand the recipe variety for the grinder, however at present, this is considered expected behaviour.

Does it work for you when you try to process iron ore or gold ore?

**Comment by xnaruto546** [comment]
Yes, it appears to be working now, thank you for your patience.
![Screen Shot 2021-04-08 at 8 26 24 PM](https://user-images.githubusercontent.com/81348104/114124382-2e61fa00-98a9-11eb-8000-5a7c27c895a1.png)
